'use strict';
let $h1 = document.querySelector('h1');
console.log($h1);
console.dir($h1);
let $id = document.querySelector('#explanation');
console.log($id);
console.dir($id);
let $class = document.querySelector('.hint');
console.log($class);
console.dir($class);
let $p = document.querySelectorAll('p');
console.log($p);
console.dir($p);
let $class2 = document.querySelectorAll('.example-link');
console.log($class2);
console.dir($class2);
