'use strict';
const fullName = 'Jeffrey Mejia Cortez';
const isCool = true;
const totalPets = 0;
console.log('value of fullName: ', fullName);
console.log('value of isCool: ', isCool);
console.log('value of totalPets:', totalPets);
console.log('typeof fullName: ', typeof fullName);
console.log('typeof isCool: ', typeof isCool);
console.log('typeof totalPets: ', typeof totalPets);
const unknown = null;
const never = console.log('value of unknown: ', unknown);
console.log('value of never: ', never);
console.log('typeof unknown: ', typeof unknown);
console.log('typeof never: ', typeof never);
