'use strict';
const width = 7;
const height = 7;
const area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 7;
const payment = 14;
const change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 7;
const midterm = 7;
const final = 7;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Jeffrey';
const lastName = 'Mejia Cortez';
let fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 14;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 7;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = (fullName += ' is the GOAT!');
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
